org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

minecraft_version=1.21.1
neo_version=21.1.77

mod_id=ftbcustombg
mod_name=FTB Custom Background
mod_license=MIT
mod_version=1.0.0
mod_group_id=dev.ftbcustombg
mod_authors=ftbcustombg
mod_description=Allows setting a custom texture as background for the FTB Quests menu.
